sudo: required
dist: trusty
language: python
python: 2.7
    #    - 3.4
    #    - 2.7
os: linux
compiler: gcc
addons:
    apt:
        packages:
            - libboost-test-dev
            - python-numpy
            - python3-numpy
            - python3-scipy
            - python-scipy
            - python3-h5py
            - python-h5py
virtualenv:
    system_site_packages: true
#before-install: git submodule update --init --recursive
install: true
script: make && make test && nosetests
