sudo: required
dist: trusty
language: python
python: 3.4
    #    - 3.4
    #    - 2.7
os: linux
compiler: gcc
addons:
    apt:
        packages:
            - libboost-test-dev
            - python3-numpy
            - python-numpy
            - python3-scipy
            - python3-h5py
            - libhdf5-serial-dev
virtualenv:
    system_site_packages: true
before-install: git submodule update --init --recursive

install:
    - pip install runtests
    - python3 setup.py install
script:
    - python3 do_the_tests.py
    - make test

deploy:
    - provider: pypi
      distributions: sdist
      user: "simeonbird"
      password:
        secure: "YtrhsYKZ1XJNil82/RWnESDPymS3NvuJdxW/yx9MixbiaEd9WNxoEkOB1IyM22Db55Fh0oGMd8UlOBJzkW1+im9OcAOKnvq1ee6QJ3TshNRB1EP1YOpY94KIQKSj0T3QpaXmVHQwfPqeIkhfiC2307v9yoWmg3FHjuq3OG7k9lrZJH9UH4EetHiQbLGl0Q+JHFNEUcBoyLoRfI9WwDAmp2IciGWc3aJoUEtn/7kC9L5ZqtkZZY9MCioL9FOZtWGQi1PaIYqaiZiRQuDhUMUzffvwBYyXylev/vGL+yHu5V533HQxkQYdq6/tBHUQio4J6hZVVbOK3+HAIoilh56ucQ2/x/xCZS5hB0zLGgAAFvGG/Wixi51eKO0xy8dbJ95UKCYsKUPU7KErtGtF0nhgj9rFmD79kDhjfb/2K8UnMoQdZQyn0NBwxPT2UMS1K03BtSOTgUjYoTp3SEq9/VAgcrc3jrOYlapsyhDd9pbx5mZBGW5RVQozpCQPnsioWJ3CvhVp82z4IV5fEFBGaVsJgeYNlGfASNjD2tSZjFcnoIlQ36AokafVAACxsfBbQ9u7rAHFEl1T7GnEuMSHdyeOF1vlWhoUHmEoT9Q6x8Z95wGogCwO4lKnmoKypqL+8CGEwkA4PQsF0cILNKMUT0g/3A79dq1essRxbgoUwKMo2CA="
      on:
          tags: true
          condition: ${TRAVIS_JOB_NUMBER##*.} == 1
